title: Notes
author: Jordan Danielewski
email: contact@jordandanielewski.com
description: "Notes et courts articles autour du développement: Ruby, Javascript, NodeJS, HTML, CSS..."
baseurl: ""
url: https://notes.jordandanielewski.com
github: jordandanielewski
linkedin: jordandanielewski
twitter: jordanielewski
google_analytics: UA-71716125-2
markdown: kramdown
kramdown:
  input: GFM
permalink: /:title/
exclude: ["README.md", "Gemfile", "Gemfile.lock"]
sass:
  style: compressed
gems:
  - jekyll-sitemap
defaults:
  -
    scope:
      path: ""
    values:
      author:
        name: Jordan Danielewski
        url: https://jordandanielewski.com
        photo: /assets/img/pic.jpg
        twitter: jordanielewski
