title: Notes
author: Jordan Danielewski
email: contact@jordandanielewski.com
description: "Notes et courts articles autour du développement: Ruby, Javascript, NodeJS, HTML, CSS..."
baseurl: ""
url: https://notes.jordandanielewski.com
github: jordandanielewski
linkedin: jordandanielewski
twitter: jordanielewski
google_analytics: UA-71716125-2
markdown: kramdown
kramdown:
  input: GFM
permalink: /:title/
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
sass:
  style: compressed
gems:
  - algoliasearch-jekyll
  - jekyll-sitemap
algolia:
  application_id: '2MO0TDI0YD'
  index_name: 'notes'
  record_css_selector: 'p,ul'
defaults:
  -
    scope:
      path: ""
    values:
      author:
        name: Jordan Danielewski
        url: https://jordandanielewski.com
        photo: /assets/img/pic.jpg
        twitter: jordanielewski
