title: Notes
author: Jordan Danielewski
email: contact@jordandanielewski.com
description: "Notes et courts articles autour du développement: Ruby, Javascript, NodeJS, HTML, CSS..."
baseurl: ""
url: https://notes.jordandanielewski.com
github: jordandanielewski
linkedin: jordandanielewski
twitter: jordanielewski
google_analytics: UA-71716125-2
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - space_after_headers
permalink: /:title/
exclude: [README.md, Gemfile, Gemfile.lock]
sass:
  style: compressed
defaults:
  -
    scope:
      path: ""
    values:
      author:
        name: Jordan Danielewski
        url: https://jordandanielewski.com
